### ISSUE TITLE
When using eNB location tool, sector 0 does not get located

### ISSUE THREAD

**Issue by ExperiencersInternational** [mroczis/netmonster-core#103]
This one has been bugging me for a while for EE and Three. Sector 0, which corresponds to band 3 1617 / band 3 1392 won't get located when using the eNB location tool.

You have to instead use the sector location tool.

As an example, I temporarily unlocated this cell on EE. 

![Screenshot_20240727-133438](https://github.com/user-attachments/assets/d4d8bd89-e59d-4da3-899d-965739efbdcf)

When editing it and locating it using the eNB tool, it will locate all the other sectors except for this one.

I have to use the sector editing tool to locate this cell due to the way NetMonster works at the moment.

**Comment by mroczis** [comment]
Hello @ExperiencersInternational, this issue has been resolved and will be available in the next NetMonster app version.
