### ISSUE TITLE
GetConnectionStatus never return SecondaryConnection

### ISSUE THREAD

**Issue by Philippe2705** [mroczis/netmonster-core#14]
Hello,

I am trying to use netMonster-Core in my android project.

NetMonster app shows LTE primary cell + secondary bands used in LTE-Advance. 
In the meantime, what I get with netMonsterCore sample is only the primary cell and "None Connection" cells, but I don't get the secondary cell. 

![image](https://user-images.githubusercontent.com/16638011/117305101-bb837900-ae7e-11eb-917c-d1e8e38e7af3.png)

![image](https://user-images.githubusercontent.com/16638011/117305050-aeff2080-ae7e-11eb-99bd-a2cbae2a3e54.png)

I am missing something or maybe it is an issue in this library ?

Have a nice day

**Comment by mroczis** [comment]
NetMonster Core provides data that are guaranteed to be correct. NetMonster App builds another layer on top of NetMonster Core which involves further post-processing which might one call "experimental", hence results on Netmonster App and NetMonster Core might differ.

Current behaviour is NetMonster Core is correct.
