### ISSUE TITLE
In case of 5g NR SA i am getting WCDMA 

### ISSUE THREAD

**Issue by SuryaChundawat** [mroczis/netmonster-core#19]
while running this app on 5g enable network with vivo x50 pro i am getting NET - WCDMA. is this right for 5g network ?

**Comment by Blykam** [comment]
Have you tried forcing NR-only in Phone Info Screen to cross-check for some buggy behaviour?

**Comment by mroczis** [comment]
Not really. If you have NetMonster app, then please head to Settings, tap 5 times on 'Version' and then hit 'Send' button. I'll check where's the issue.

**Comment by SuryaChundawat** [comment]
From Api version 30 only NR Kpis fully supported.
