### ISSUE TITLE
Show all sectors of a tower again

### ISSUE THREAD

**Issue by Blykam** [mroczis/netmonster-core#22]
This GitHub page is more for the API than the Netmonster app directly, but still:
In the past Netmonster showed all sectors of a selected cell tower in the map screen. In an update that feature was removed and replaced by only showing logged sectors at a tower.
It was great to look in the map what sectors there are.
Now the app still knows all that through its databases, but does not show it to the user in that great extent.

Could this be added in again?

**Comment by mroczis** [comment]
NetMonster-exclusive issues do not really belong here. Feature you are mentioning is still present. Maybe you expect to see all sectors but NetMonster shows only logged ones since querying over whole DB of imported cells takes ages.
