### ISSUE TITLE
Which devices now support PhysicalChannelConfig?

### ISSUE THREAD

**Issue by sinak** [mroczis/netmonster-core#29]
The source code mentions 3 devices (Pixel 3 XL, OnePlus 6T, Xiaomi Mi 9T) that support the PhysicalChannelConfig API.

Are there any newer devices (with 5G NR support) that also support the PhysicalChannelConfig API?

**Comment by mroczis** [comment]
As far as I know there's no device that supports 5G and has correct Android version that provides `PhysicalChannelConfig`.
