### ISSUE TITLE
IConnection aggregatedCells list is alway empty

### ISSUE THREAD

**Issue by cedricf25** [mroczis/netmonster-core#3]
Hi,

Array aggregatedCells in PrimaryCOnnection is always empty.

And Bandwith in neighbourgs cells is not mapped. My netmonster app have this info.

Can you check ?

Thanks

**Comment by mroczis** [comment]
Hi,
this feature is not implemented yet. Field `PrimaryConnection.aggregatedCells` is part of initial design of the library and might change before stable version is released. If you are already building your codebase using NetMonster Core you can obtain cells serving as secondary for each subscription using this code:

```kotlin
 NetMonsterFactory.get(context).getCells()
   .groupBy { it.subscriptionId }
   .mapValues { (subId, cells) -> cells.filter { it.connectionStatus is SecondaryConnection } }
```

Please note that NetMonster app currently uses some guessing techniques that do not provide 100 % correct outputs and they will probably not appear in codebase of NetMonster Core.

**Comment by mroczis** [comment]
External database that links `earfcn`, `pci` and location of base stations is required to properly identify secondarily serving cells. For this reason additional post-processing cannot be implemented in the library.

If you are willing to guess which cells with `NoneConnection` could have `SecondaryConnection`, then implement algorithm that will be able give you `eci` from `pci` + current location. Then you can compare `cid` and guess which cell is secondarily serving. Please note that each network provider uses different rules when assigning `cid` to each `eNb`.

**Comment by jidanni** [comment]
I am thinking that now in 2023, maybe half the cells in the United States are affected by this bug, and thus being marked invalid and thrown away. See https://github.com/zamojski/TowerCollector/issues/205 @zamojski
