### ISSUE TITLE
How to have band aggragation

### ISSUE THREAD

**Issue by cedricf25** [mroczis/netmonster-core#30]
Hello,

I can't find where is the bandwidth and frequency aggregation in lib, to get for example : 20+10+15 mhz and the frequency assiociated ?

Thanks MrOczis !
Cedric

**Comment by mroczis** [comment]
It's part of the `ServiceState` object, use `ITelephonyManagerCompat` to retrieve it.

More at:
https://developer.android.com/reference/android/telephony/ServiceState#getCellBandwidths()
