### ISSUE TITLE
Sample code, how to use netmonster core

### ISSUE THREAD

**Issue by rkkilari** [mroczis/netmonster-core#32]
HI, I am new this library and android. Is there any sample code to show how to use this library? This will help new comers. TIA.

**Comment by mroczis** [comment]
Basic samples are in this repo's readme. But if you want to have a depper look start with `NetMonsterFactory` which allows you to get `ITelephonyManagerCompat` and `ISubscriptionManagerCompat`. Those two classes just backport several methods from Android's `TelephonyManager` and `SubscriptionManager`.

Third object you can get is `INetMonster` - this class adds a new behaviour. Refer to individual method documentations for precise description.
