### ISSUE TITLE
Is the library still maintained?

### ISSUE THREAD

**Issue by zamojski** [mroczis/netmonster-core#33]
Is the NetMonster Core library still being developed? I've seen many updates to NetMonster app but no changes here for almost half a year.

**Comment by mroczis** [comment]
Development of this library depends on stuff added to AOSP. Latest Android version didn't bring anything that would help post-process data hence it looks a bit dead.

**Comment by zamojski** [comment]
Ok, thanks for reply. I understand the reason now. What about the 'work in progress' message at the top of readme? Do you plan some activities, for example publishing on maven?

**Comment by mroczis** [comment]
You are right, will update README and publish lib to mavenCentral.

**Comment by mroczis** [comment]
I've just published library to Maven Central.
