### ISSUE TITLE
S22 (Exynos) reports TAC with wrong endianness

### ISSUE THREAD

**Issue by HandyMenny** [mroczis/netmonster-core#37]
Since Android 12 update, new api (CellSource.ALL_CELL_INFO) reports LTE TAC with wrong byte order.

Example:
TAC is 0x55F1 (2201), api reports 0xF155 (61781)
TAC is 0x4658 (18008), api reports 0x5846 (22598)

Netmonster debug log: [report.txt](https://github.com/mroczis/netmonster-core/files/8391546/report.txt)

**Comment by mroczis** [comment]
Looks like Samsung messed up byte order when propagating data from RIL to Android interfaces. Can you check if this problem also occurs on other network types (GSM, WCDMA, NR)?

**Comment by HandyMenny** [comment]
> Can you check if this problem also occurs on other network types (GSM, WCDMA, NR)?

2G and 3G have the same exact issue. NR is a bit complicated, SA isn't widespread here.

I can tell you that S21 exynos and S21 FE 5G qualcomm don't seem to have this problem.

However the old api reports the right tac, what about adding a specific check (on byte order) for samsung exynos with android 12?

**Comment by mroczis** [comment]
Thanks, gonna have a look what can be done. The problem is that old API does not work when display is off so some persistence-based solution must be introduced.

Just for the record `samsung SM-S908B (b0sxeea)` is also affected.

**Comment by mroczis** [comment]
Fix tested on `b0sxeea`. Feature is toggleable as requested, for more info refer to linked commit.

When it comes to other stuff - NetMonster Core is made to be simple without any further excessive configuration. You can always fork the library or build another layer on top of it if you need some other specific post-processing. 
Your "NR band hints" is one of the cases that cannot be solved globally. But if you are focusing on one country/continent then loads of stuff is more clear (e.g. guessing band from the EARFCN). However, I agree there could be a native way how to alter band deduction of EARFCN.
