### ISSUE TITLE
Some Huawei devices report NR signal in absolute value

### ISSUE THREAD

**Issue by HandyMenny** [mroczis/netmonster-core#42]
Some Huawei devices, specifically HUAWEI ELS-NX9 API 29, report NR (both NSA and SA) signal values in absolute value.
SS-RSRP and SS-RSRQ are affected for sure, while SS-SINR isn't affected. Extract of netmonster debug log attached.

Here you will find a quick fix that has been tested and solves the issue: https://github.com/HandyMenny/netmonster-core/commit/81c1df179deb7cde986e10eb6a1f0a98cf84c748
The values after the fix were compared to those read directly from the modem (bypassing Android and RIL), so I can confirm that the issue is really solved

[netmonster-debug.txt](https://github.com/mroczis/netmonster-core/files/8653084/netmonster-debug.txt)

**Comment by HandyMenny** [comment]
Another log from the same device:
[Netmonster-debug-nsa.txt](https://github.com/mroczis/netmonster-core/files/8653159/Netmonster-debug-nsa.txt)

In this case netmonster reports the right SS-RSRP, I guess because it's reading it from another source (android.telephony.SignalStrength?)

**Comment by mroczis** [comment]
Thanks for the contribution. I have just merged your branch into `master`.
