### ISSUE TITLE
Can a LTE primary cell have TAC and ECI null ?

### ISSUE THREAD

**Issue by Eimji** [mroczis/netmonster-core#45]
Hello,

Thanks for sharing your libray. I ran into a situation where a LTE cell reported as PrimaryConnection had a null value both for TAC and ECI. I don't know if this a bug or this case may happen. FYI, I'm using an Oppo Find X5 pro with two SIM cards (one with subscription supporting only LTE, and the other SIM can support 5G). The issue occurrend on the first SIM supporting only LTE.

Thanks for your answer.

**Comment by mroczis** [comment]
Yes, this can happen. It depends on modem and low-level implementation. I bumped into several devices that for a short period of time just return PCI.

**Comment by Eimji** [comment]
Thank you!

**Comment by mroczis** [comment]
Those data are still valid. Device just knows PCI and other identifiers will hopefully arrive within next update. From the point of data validity it's still better to provide something partial than nothing.
It's up to you if such incomplete data fit your use-case or not. If not then you can always perform filtration on your side.

**Comment by Eimji** [comment]
Thanks! I understand now.
