### ISSUE TITLE
NetMonster constantly logs the same NR SA sites over and over

### ISSUE THREAD

**Issue by eladts** [mroczis/netmonster-core#62]
This happens on my Pixel 7 with Google Fi service, which uses the T-Mobile US network. I'm attaching a log file to demonstrate.

[NTM_01_02_11_46.zip](https://github.com/mroczis/netmonster-core/files/10333219/NTM_01_02_11_46.zip)

**Comment by mroczis** [comment]
Can you send me a NetMonster App bug report please?
In order to obtain it head to Settings, tap 5 times on 'Version' and then hit the send button. Make sure you are connected to 5G cell that gets duplicated when creating the bug report.

**Comment by eladts** [comment]
Sure. As far as I can tell, this happens every time the phone is connected to NR SA.

[report.txt](https://github.com/mroczis/netmonster-core/files/10531260/report.txt)

**Comment by eladts** [comment]
This issue still exists with version 2.22.0.

**Comment by Beat-YT** [comment]
@mroczis update?

**Comment by Beat-YT** [comment]
![Screenshot_20230323-124607.jpg](https://user-images.githubusercontent.com/66485277/227277013-d3bf77c6-d39d-46a2-82a7-32a5e27db6dd.jpg)

Happening here too
