### ISSUE TITLE
Band in cell location: show both

### ISSUE THREAD

**Issue by jidanni** [mroczis/netmonster-core#65]
The "band in cell location" preference, we can pick 2100 or B1, but what if we want both? Perhaps add an additional choice to show both.

**Comment by Rekoo52anzi** [comment]
> The "band in cell location" preference, we can pick 2100 or B1, but what if we want both? Perhaps add an additional choice to show both.

Duplicate of #

> [A]()

**Comment by mroczis** [comment]
This is not related to NetMonster Core since such functionality is UI-related and only available NetMonster App. NetMonster Core does exposed both information if available. I'll consider adding such option into apps settings.

**Comment by jidanni** [comment]
OK!

(Hmmm, all I can find other is https://github.com/mroczis/netmonster-web .
It seems there is no proper place to file NetMonster App issues.)
