### ISSUE TITLE
NR 5MHz alignment check, it's valid?

### ISSUE THREAD

**Issue by HandyMenny** [mroczis/netmonster-core#78]
I know that this problem has been solved at the root by exposing all the bands that "fits".

But since this alighnment check is still there (for those using the old map), I wanted to ask about its validity.

For example, these are all the Italian SSB-ARFCNs (present and past) that I'm aware of:

Band | SSB-ARFCN | 5MHz Alignment check
-- | -- | --
28 | 152210 | Y
28 | 152690 | Y
28 | 154570 | Y
28 | 156510 | Y
3 | 365530 | Y
3 | 368890 | Y
3 | 371530 | Y
1 | 427470 | Y
1 | 432050 | Y
1 | 432500 | Y
7 | 535010 | Y
7 | 537410 | Y
78 | 629472 | N
78 | 629856 | N
78 | 631968 | N
78 | 632352 | N
78 | 632736 | N
78 | 636192 | N
78 | 636480 | Y
78 | 636576 | N
78 | 636768 | N
78 | 638016 | N
78 | 638976 | N
78 | 639360 | Y
78 | 640320 | Y
78 | 640704 | N
78 | 642048 | N
78 | 643296 | N
78 | 644640 | Y
78 | 645312 | N
78 | 648384 | N
78 | 650654 | N
78 | 650688 | N
257 | 2068507 | N
257 | 2070235 | N

While it seems to work very well for bands < 3GHz, it doesn't seem to work as well for bands > 3GHz. (By the way, bands > 6GHz are missing in BandNrTable). 
Note that we don't have so many frequency blocks in Italy, it's just that the SSB-ARFCNs have changed over time or are different for different RAN vendors.

**Comment by mroczis** [comment]
5MHz alignment check is implemented just to help detect possible band and it generally works for lower frequencies. It's definitely not applicable globally, especially when frequency blocks are as wide as 400 MHz. In such cases national regulators assign non-align blocks or even carries fragment them further.

**Comment by HandyMenny** [comment]
Yes, you are right. I just wanted to point out that in some cases that check is "often" misleading.

(Btw the blocks above are almost all 5MHz aligned, it's just that there is no requirement to have the SSB 5MHz aligned)
