### ISSUE TITLE
Cannot get cell's location related data(Have only tried for LTE)

### ISSUE THREAD

**Issue by pandeybivek101** [mroczis/netmonster-core#84]
I have to obtain cell data (both strengths and location). I tried to use this SDK. 

import cz.mroczis.netmonster.core.model.cell.ICell
import android.content.Context
import cz.mroczis.netmonster.core.feature.merge.CellSource

NetMonsterFactory.get(context).apply {
            val allSources : List<ICell> = getCells() // all sources
            val subset : List<ICell> = getCells( // subset of available sources
                CellSource.ALL_CELL_INFO,
                CellSource.CELL_LOCATION
            )

            print("----------------------------------------------")
            Log.d("NTM-RES", " \n${subset.joinToString(separator = "\n")}")
            print("----------------------------------------------------")
        }

when I used above function cell info data were present there but location related information were missing there you can see the result below.

CellLte(network=Network(mcc=244, mnc=12, iso=FI), eci=1897729, tac=201, pci=43, band=BandLte(downlinkEarfcn=1598, number=3, name=1800), aggregatedBands=[], bandwidth=null, signal=SignalLte(rssi=-71, rsrp=-81.0, rsrq=-10.0, cqi=11, snr=5.0, timingAdvance=null), connectionStatus=PrimaryConnection(), subscriptionId=2, timestamp=765942574)

 CellLte(network=Network(mcc=244, mnc=12, iso=FI), eci=null, tac=null, pci=8, band=BandLte(downlinkEarfcn=1598, number=3, name=1800), aggregatedBands=[], bandwidth=null, signal=SignalLte(rssi=-71, rsrp=-82.0, rsrq=-11.0, cqi=null, snr=null, timingAdvance=null), connectionStatus=NoneConnection(), subscriptionId=2, timestamp=765942574)
 
 
 how can I get the location of the cells? is it issue of new release? FYI I am new to android studio.

**Comment by mroczis** [comment]
NetMonster Core does not provide location of cell towers.
