### ISSUE TITLE
Impossible to add location to NR SA sites

### ISSUE THREAD

**Issue by eladts** [mroczis/netmonster-core#85]
If I try with NetMonster 2.22.2 to manually add a location to an NR site from the log it lets me add a location on the map and save it, but the location isn't actually saved and the site remains without location information.

**Comment by nlgntr** [comment]
Hello, sorry post after so long but it looks like this is still an issue. I've attempted to add a location to an NR site, and after saving nothing has changed.

My device: Pixel 9 Pro XL
Netmonster version: 3.1.1
