### ISSUE TITLE
No carrier aggregation bandwidth data with NR SA

### ISSUE THREAD

**Issue by eladts** [mroczis/netmonster-core#86]
NetMonster 2.22.2 only shows carrier aggregation bandwidth data data for LTE or LTE + NR NSA. This information isn't shown at all for NR SA, even though other apps such as CellMapper are showing it.

![image](https://github.com/mroczis/netmonster-core/assets/6475871/3db2941d-c904-4907-baab-d71e2d6f4697)

**Comment by damcej** [comment]
D

**Comment by mroczis** [comment]
Thanks for letting me know. This issue will be resolved in an upcoming NetMonster release.
