### ISSUE TITLE
Yes we often know the neighbors' cell ID all along

### ISSUE THREAD

**Issue by jidanni** [mroczis/netmonster-core#94]
In the first image, all we know is the PCI, 357. We don't know the cell ID (eNb).
![Screenshot_20240221_175103_NetMonster.jpg](https://github.com/mroczis/netmonster-core/assets/1230959/1767f3cc-2aec-4489-a89c-4ba165b37f38)

Well, in fact we really do know the Cell ID (eNb). It's right there in the log, from a little earlier!

![Screenshot_20240221_175158_NetMonster.jpg](https://github.com/mroczis/netmonster-core/assets/1230959/871b95b2-6005-4f09-9075-d9d6999ddfef)

So you really should show it to the user too, when displaying that PCI, as it's not just some unknown quantity.

In fact, all the other cell ID apps out there make the same sad mistake too.

It's just like, "What is this weird phone number that is calling me?"

Well, if you remembered (via a database), it's your grandmother who just called you earlier this afternoon!

"Are you sure? Maybe it's the same number but a different area code?"

Yes even the area code matches.

Even if they called you 5 years ago, it's still your grandmother probably...

**Comment by ExperiencersInternational** [comment]
NetMonster already does this, but you have to locate sites. For some reason, doesn't do this on 2G though.

I don't know whether this is necessary on premium plans given that it automatically located stuff.

I've censored some information for privacy information but when you've located neighbouring cells, it'll show:

> PCI eNB:Sector               EARFCN RSRP/RSRQ
> [Band] Location

![Screenshot_20240731-134640](https://github.com/user-attachments/assets/21cbff3f-e831-4b35-8187-d008a8bb5909)
