### ISSUE TITLE
Show cell ID on graphs

### ISSUE THREAD

**Issue by jidanni** [mroczis/netmonster-core#97]
The cell ID needs to be shown somewhere on this page.

![Screenshot_20240401_152702_NetMonster.jpg](https://github.com/mroczis/netmonster-core/assets/1230959/d692c9d5-be26-44a8-8165-d16e75cf39d5)

Let's say we take a few screenshots. Later on we can't tell which cell IDs they belong to. All we can tell is they were LTE etc.

**Comment by mroczis** [comment]
Added!
