### ISSUE TITLE
Grammar 

### ISSUE THREAD

**Issue by jidanni** [mroczis/netmonster-core#99]
Here instead of "a" , you want to say "and" . 
Also I would say "lots" , instead of "loads" . It sounds a tiny bit more professional.

![Screenshot_20240401_064152_NetMonster.jpg](https://github.com/mroczis/netmonster-core/assets/1230959/bb8fe7db-a7a4-4e1e-bb4c-6aa0a8126214)

**Comment by mroczis** [comment]
Fixed, thanks!
